site_name: ops docs
theme:
  name: windmill
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tabbed
  - admonition
  - footnotes
  - toc:
      permalink: true
