site_name: ops docs
theme:
  name: material
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tabbed
  - admonition
  - footnotes
  - toc:
      permalink: true

plugins:
  - search
  - mkdocs-add-number-plugin:
      strict_mode: False # 模式选项
      increment_pages: false
      increment_topnav: false
      # excludes:
      #     - '*'
      # includes:
      #     - sql/
      #     - mybatis\
      # order: 1
